// Students
export const ALL_STUDENTS_REQUEST = 'ALL_STUDENTS_REQUEST';
export const ALL_STUDENTS_DATA = 'ALL_STUDENTS_DATA';
export const ALL_STUDENTS_ERROR = 'ALL_STUDENTS_ERROR';

// Single Student
export const SINGLE_STUDENT_REQUEST = 'SINGLE_STUDENT_REQUEST';
export const SINGLE_STUDENT_DATA = 'SINGLE_STUDENT_DATA';
export const SINGLE_STUDENT_ERROR = 'SINGLE_STUDENT_ERROR';
